version: '3.8'

services:
  web:
    image: chillicoretemplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "25:25"
    environment:
      - ASPNETCORE_ENVIRONMENT=Debug
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=chillicoretemplate
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    volumes:
      - ./devops/aspnetapp.pfx:/app/aspnetapp.pfx
