<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;Staging;Develop</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1591;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AppleAuth.NET" Version="1.0.8" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.101.80" />
    <PackageReference Include="ChilliSource.Cloud.AWS" Version="2.0.0-alpha0015" />
    <PackageReference Include="ChilliSource.Cloud.Azure" Version="2.0.0-alpha0029" />
    <PackageReference Include="ChilliSource.Cloud.ImageSharp" Version="2.0.0-alpha0008" />
    <PackageReference Include="ChilliSource.Cloud.Web" Version="2.0.0-alpha0044" />
    <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
    <PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
    <PackageReference Include="LazyCache" Version="2.4.0" />
    <PackageReference Include="LazyCache.AspNetCore" Version="2.4.0" />    
    <PackageReference Include="DataTables.AspNet.AspNetCore" Version="2.0.2" />
	<PackageReference Include="MailKit" Version="4.8.0" />
	<PackageReference Include="Microsoft.Azure.NotificationHubs" Version="4.2.0" />
    <PackageReference Include="AsyncEnumerator" Version="4.0.2" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.3.8" />
    <PackageReference Include="Mjml.Net" Version="3.8.0" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="112.1.0" />
    <PackageReference Include="Sqids" Version="3.1.0" />
    <PackageReference Include="Stripe.net" Version="47.0.0" />
    <PackageReference Include="Twilio" Version="7.7.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ChilliCoreTemplate.Data\ChilliCoreTemplate.Data.csproj" />
    <ProjectReference Include="..\ChilliCoreTemplate.Models\ChilliCoreTemplate.Models.csproj" />
  </ItemGroup>

</Project>
