<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;Staging;Develop</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1591;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ChilliSource.Cloud.Core" Version="2.0.0-alpha0163" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ChilliCoreTemplate.Models\ChilliCoreTemplate.Models.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
